project_id = "kgfxsxwkdbtvkanopeuf"

[functions.fetch-stock-data]
verify_jwt = false

[functions.stock-ai-prediction]
verify_jwt = false

[functions.stock-chat]
verify_jwt = false

[functions.fetch-historical-data]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false